### ISSUE TITLE
Retos Python Study Group

### ISSUE THREAD

**Issue by jevillanueva** [GitHalex/psg-example#1]
Hola!

Veo que aun faltan retos del python study group....  
Me gustaria invitarte a que continues 😄 
Aquí encontrarás todas las sesiones y sus retos  https://study.pylapaz.org/
No te desanimes!! estare atento a tus retos, animo!!! 

---
Feedback:

De la sesión 01 faltan los retos 1 y 2
La sesión 2 y 3 esta super bien lo hiciste muy bien .... fun fact: yo tb soy de potosi pero vivo en lpz... xD

Tienes aun los retos disponibles de la sesión 4 hasta la 10 disponibles
No te desanimes vas muy bien
Si tienes dudas estare en el grupo de whatsapp para responder dudas y por aqui tambien puedes escribirme
Estare atento a tu repo

> El arte de la programación es el arte de organizar la complejidad, de dominarla y de reducirla. - Edsger Dijkstra

**Comment by GitHalex** [comment]
Gracias Jhonathan por el feedback pensé que no estaban revisando 😅, está
semana me pongo al Día saludos

**Comment by jevillanueva** [comment]
si ando revisando aunq de amanecidad y algunas veces :D
